import "./globals.css";

import type { Metadata } from "next";
import Link from "next/link";
import { NavigationInterceptionProvider } from "@yaredfall/next-navigation-interception";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                    {children}
            </body>
        </html>
    );
}
